# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "30017:27017"
    volumes:
      - ./mongo/db :/data/db
    privileged: true
    container_name: mongo-com


  postwoman:
    image: hoppscotch/hoppscotch
    ports:
      - "30083:3000"
   # command: "npm run dev"
    privileged: true
    container_name: postwoman-com


  redis:
    image: redis
    ports:
      - "30079:6379"
    privileged: true
    volumes:
      - ./redis/data:/data
      - ./redis/etc/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    container_name: redis-com

  mongo-express:
    image: mongo-express
    restart: always 
    ports:
      - 30081:8081
    privileged: true
    container_name: mongoexpress-com
  nginx:
    image: nginx
    ports:
      - "30080:8080"
    privileged: true
    environment:
      - NGINX_HTTP_PORT_NUMBER=8080
      - NGINX_HTTPS_PORT_NUMBER=8443    
    volumes:
      - ./nginx/opt/dist:/opt/dist
      - ./nginx/opt/log:/var/logs
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
    #command: 
    container_name: nginx-com
  
  easy-mock:
    image: easymock/easymock
    privileged: true
    command: /bin/bash -c "npm start"
    links:
      - mongo:mongodb
      - redis:redis
    ports:
      - 30082:7300
    volumes:
      - ./easy-mock/logs:/home/easy-mock/easy-mock/logs
      - ./easy-mock/production.json:/home/easy-mock/easy-mock/config/production.json
    container_name: mock-com

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-com
    privileged: true
    volumes: 
      - /etc/localtime:/etc/localtime:ro    
      - ./mysql/data:/var/lib/mysql
      # - ./mysql/mysql-files:/var/lib/mysql-files/
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
    environment:      
      - MYSQL_ROOT_PASSWORD=111111
    command: mysqld 
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4 
            --collation-server=utf8mb4_unicode_ci
    ports:
       - '33306:3306'